# Tank-shaped world configuration (TOML format)
# Top-down view of a tank made from rectangular obstacles

width = 30.0
height = 20.0

# Tank Body (main hull)
[[obstacles]]
pos = [0.0, 0.0]
size = [8.0, 4.0]

# Tank Turret (on top of body)
[[obstacles]]
pos = [0.5, 0.0]
size = [3.0, 3.0]

# Tank Cannon (long barrel extending forward)
[[obstacles]]
pos = [4.5, 0.0]
size = [5.0, 0.6]

# Left Track (treads)
[[obstacles]]
pos = [0.0, 2.5]
size = [9.0, 0.8]

# Right Track (treads)
[[obstacles]]
pos = [0.0, -2.5]
size = [9.0, 0.8]

# Rear armor (back of tank)
[[obstacles]]
pos = [-4.5, 0.0]
size = [1.0, 4.5]

# Left track detail (front)
[[obstacles]]
pos = [4.0, 2.5]
size = [1.5, 1.2]

# Right track detail (front)
[[obstacles]]
pos = [4.0, -2.5]
size = [1.5, 1.2]

# Left track detail (rear)
[[obstacles]]
pos = [-4.0, 2.5]
size = [1.5, 1.2]

# Right track detail (rear)
[[obstacles]]
pos = [-4.0, -2.5]
size = [1.5, 1.2]
